version: "3"
services:
  api:
    container_name: MedableAPI
    restart: always
    networks:
      - api-net
    image: gcr.io/utopian-genius-111023/github.com/gastonrobledo/test-todo-api:33723f3
    environment:
      - MONGODB_URI=mongodb://mongo/medable-api
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    networks:
      - api-net
    container_name: Mongo
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo-data:
networks:
  api-net: