apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: api
  name: web
spec:
  ports:
  - name: http
    port: 80
    targetPort: 5000
  selector:
    io.kompose.service: api
  type: LoadBalancer
status:
  loadBalancer: {}